# Overrides for GitHub Pages deployment
# Use together with _config.yml via JEKYLL_CONFIG="_config.yml,_config.github.yml"

# Public site URL on GitHub Pages
url: "https://victorigp.github.io"

# Subpath for project pages
baseurl: "/videoteca"

# Avatar path must include baseurl on GH Pages because some theme spots don't pipe through `relative_url`.
# This avoids htmlproofer failing with "/assets/img/avatar.png does not exist" in _site/videoteca/* pages.
avatar: /videoteca/assets/img/avatar.png
